version: '3.7'

services:
  app:
    container_name: money-note
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
